sudo: false
language: rust
rust: nightly
script:
- cargo build
- cargo test
after_success:
- .travis/release.sh
env:
  global:
  - secure: iEGoVGb3OeqSqP4UP7nbLtMEmGi9JgI0nxjrpRrSg22pCCa+lMIIiYp9gY2558pwAbcxaJpahmTt3lYqe2wdKfXlGWRB7Tz99FR8lX+vRXpgxDLg1Sz8BAnN7X9bu+AGL/INwYOe6tVncXcQgKn4uSTYa001CqhlwPzMmtGSw/w=
  - secure: eKEXvvZrTIKGV7LouFW0EfjFPd09OgEI3Y6Z5QsWdEdv73zMvXzjz9xHu+9AmYirI8m/e0v2/RXefP/elcxjLKBa61b1MC/shQPjpbaqC4Y6UTQh5If1X/QN88cbc+VldD2dKgjP5gRX72TAfHoO466NLIxxigKkZJQsOawOVUs=
deploy:
  provider: releases
  api_key:
    secure: hXEp+2VHRznxkeaJhb3i9wld/Nw40U2OOYewbyBmpxKEyvP78Ae42kzKOaOHqgFj54BgAb7fQVHO7bdjYcTSum75rh4iz0dplmKTZKWKj1NO1HgvXbwTdfN6VkALttoTMmegW9ngzxZxkrpF3ezPlADglv41mkzW5Ewwf4tPhJQ=
  file: /target/release/seax
  on:
    repo: hawkw/seax
